"""agrega activo a socios

Revision ID: 40a42d6be031
Revises: b6f165d5459a
Create Date: 2026-09-09 03:59:38.739420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a42d6be031'
down_revision: Union[str, None] = 'b6f165d5459a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socios', 'activo')
    # ### end Alembic commands ###
