"""agrega socio_id a usuarios

Revision ID: 9ba6052ab455
Revises: ccaa8ca79941
Create Date: 2026-09-11 01:48:26.710160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba6052ab455'
down_revision: Union[str, None] = 'ccaa8ca79941'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('socio_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'usuarios', 'socios', ['socio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'socio_id')
    # ### end Alembic commands ###
