"""agrega documento y telefono a socios

Revision ID: b6f165d5459a
Revises: 4faaee538081
Create Date: 2026-09-09 03:13:12.769456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f165d5459a'
down_revision: Union[str, None] = '4faaee538081'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('documento', sa.String(), nullable=False))
    op.add_column('socios', sa.Column('telefono', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'socios', ['documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'socios', type_='unique')
    op.drop_column('socios', 'telefono')
    op.drop_column('socios', 'documento')
    # ### end Alembic commands ###
